### ISSUE TITLE
Scoped snippet for migrations

### ISSUE THREAD

**Issue by batisteo** [vscode-django/vscode-django#11]
```toml
[[snippets]]
prefix = "run_python"
body = "migrations.RunPython($1, ${2:migrations.RunPython.noop}),"

[[snippets]]
prefix = "run_python_code"
body = """
def $1(apps, schema_editor):
    ${2:Model} = apps.get_model("${3:app}", "$2")
    $0
"""
```
